build:
  version: "1.0"

accounts:
  message: "Welcome to GoldBank accounts related Production APIs"
  contactDetails:
    name: "John Doe - Prod"
    email: "john@goldbank.com"
  onCallSupport:
    - (123) 123-1234
    - (123) 123-1234
