build:
  version: "1.0"

loans:
  message: "Welcome to GoldBank Cards related Prod APIs "
  contactDetails:
    name: "suraj sharma - Developer"
    email: "suraj@goldbank.com"
  onCallSupport:
    - (123) 123-1234
    - (123) 123-1234