build:
  version: "2.0"

loans:
  message: "Welcome to GoldBank loans related QA APIs"
  contactDetails:
    name: "John Doe - QA"
    email: "john@goldbank.com"
  onCallSupport:
    - (123) 123-1234
    - (123) 123-1234