spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///C://Udemy//workspace//goldbank-config"
        git:
          uri: "https://github.com/surajsharma286/goldbank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8071
